name: build

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup `node 16.x`
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run `npm install`
        run: npm install
      - name: Build
        run: npm run ci:build
      - name: Lint
        run: npm run ci:lint
      - name: Test
        run: npm run ci:test
